// Package cli wires the pn binary's cobra command tree.
package cli

import (
	"context"
	"errors"
	"io"
	"os"
	"os/signal"
	"syscall"

	"github.com/spf13/cobra"

	"github.com/phillipgreenii/nix-repo-base/modules/pn/internal/telemetrycfg"
)

// addOSXCmdHook is set by osx_darwin.go's init() on darwin. Nil on other platforms.
var addOSXCmdHook func(*cobra.Command)

// Execute builds the root command tree and runs it against os.Args[1:].
// version must be a real version string from mkVersion; "dev" is rejected.
func Execute(version string) error {
	args := os.Args[1:]
	res := telemetrycfg.Prepare(context.Background(), args, os.Getenv, os.Geteuid() == 0, os.Stderr)
	return executeWith(version, args, os.Stdout, os.Stderr, res)
}

// executeWithVersion is the test seam — caller passes args, stdout, stderr writers.
// Telemetry is resolved from the process environment, exactly as Execute does;
// tests that must not see a developer's real configuration set HOME/XDG_* and
// unset OTEL_* first.
func executeWithVersion(version string, args []string, stdout, stderr io.Writer) error {
	res := telemetrycfg.Prepare(context.Background(), args, os.Getenv, os.Geteuid() == 0, stderr)
	return executeWith(version, args, stdout, stderr, res)
}

// executeWith runs the command tree with an already-resolved telemetry
// configuration.
func executeWith(version string, args []string, stdout, stderr io.Writer, res telemetrycfg.Resolution) error {
	if version == "dev" {
		return errors.New("pn: built with version=\"dev\"; this binary was built outside the Nix derivation. Use `nix build .#pn` for a real binary")
	}

	// Cancel the command's context on SIGINT/SIGTERM so a Ctrl-C during a
	// fan-out (e.g. `pn workspace update`) propagates cancellation to the
	// in-flight subprocesses via cmd.Context(), instead of being ignored until
	// each child exits on its own (bead pg2-x3r0a). A second signal restores the
	// default behavior (immediate termination).
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	state := telemetrycfg.NewRunState(res)
	ctx = telemetrycfg.WithRunState(ctx, state)

	root := newRootCmd(version)
	root.SetArgs(args)
	root.SetOut(stdout)
	root.SetErr(stderr)
	root.SilenceUsage = true
	root.SilenceErrors = true
	err := root.ExecuteContext(ctx)

	// `trace: <id>` goes to stderr only (never stdout), and only under -v or
	// PN_TRACE_HINT=1; it needs a trace id, which exists only when the root
	// span recorded one via RunState.SetTraceID.
	telemetrycfg.WriteHint(stderr, state, res.Verbose, os.Getenv)
	return err
}

// addTelemetryFlags registers the global telemetry flags. The VALUES are read
// by telemetrycfg.ScanArgs before cobra runs (telemetry must exist before the
// command tree does); registering them here makes cobra accept them and list
// them in --help.
func addTelemetryFlags(root *cobra.Command) {
	pf := root.PersistentFlags()
	pf.Bool("no-telemetry", false, "disable OpenTelemetry export for this run (also: PG_NIX_LOG_DISABLE=1, OTEL_SDK_DISABLED=true)")
	pf.String("otlp-endpoint", "", "OTLP/HTTP collector endpoint for this run (overrides OTEL_EXPORTER_OTLP_ENDPOINT and ~/.config/pn/telemetry.toml)")
	pf.BoolP("verbose", "v", false, "verbose diagnostics: print the trace id hint and telemetry reachability notes on stderr")
}

// rootLong is the `pn --help` text. Its escape-hatch table is the single
// authoritative list of telemetry controls; modules/pn/README.md carries the
// same table (ADR 0028). Keep the two in sync.
const rootLong = `pn-workspace multi-repo Nix workflow tool.

Telemetry (optional, OpenTelemetry over OTLP/HTTP to a local collector) is ON
only when an endpoint resolves: --otlp-endpoint, then OTEL_EXPORTER_OTLP_ENDPOINT,
then ~/.config/pn/telemetry.toml (generated by the home-manager module
phillipgreenii.pn.telemetry). With no endpoint pn creates no exporter, opens no
connection and behaves exactly as without telemetry.

Telemetry escape hatches:
  phillipgreenii.pn.telemetry.enable = false   Off permanently (removes the config file and the wrapper package)
  pn --no-telemetry                            Off for one pn run
  PG_NIX_LOG_DISABLE=1                         Off for pn; the wrapper execs CMD unmodified
  pg-nix-log-wrapped --check                   Prints the resolved endpoint, reachability and log-dir writability
  OTEL_SDK_DISABLED=true                       Both binaries off
  PG_NIX_LOG_DEBUG=1                           The wrapper prints diagnostics to stderr`

func newRootCmd(version string) *cobra.Command {
	root := &cobra.Command{
		Use:     "pn",
		Short:   "pn-workspace multi-repo Nix workflow tool",
		Long:    rootLong,
		Version: version,
	}
	root.SetVersionTemplate("{{.Version}}\n")
	addTelemetryFlags(root)
	addWorkspaceCmd(root)
	addStoreCmd(root)
	if addOSXCmdHook != nil {
		addOSXCmdHook(root)
	}
	return root
}
