# mkGoBuilders — Go-equivalent of mkBashBuilders. Provides:
#   - mkGoApp: build a Go app via gomod2nix (buildGoApplication), keyed to its
#     own source digest (ADR 0006) so editing source gives per-edit `--version`
#     attribution without rebuilding sibling packages. Dependencies are vendored
#     as per-module content-addressed FODs read from a committed `gomod2nix.toml`
#     (ADR 0008), so there is no `vendorHash` to bump and no whole-repo FOD to
#     invalidate.
#   - mkGoBinary: opinionated wrapper over mkGoApp that also generates a man
#     page (help2man) and shell completions.
{
  pkgs,
  lib ? pkgs.lib,
  # `self` is accepted for signature parity with mkBashBuilders but unused here.
  ...
}:
assert
  pkgs ? buildGoApplication
  || throw ''
    mkGoBuilders requires pkgs.buildGoApplication (gomod2nix's overlay).
    Either:
      - Import phillipgreenii-nix-base.flakeModules.gomod2nix-overlay and
        apply self.overlays.gomod2nix to your pkgs, OR
      - Declare inputs.gomod2nix directly and apply
        inputs.gomod2nix.overlays.default to your pkgs.
  '';
rec {
  # Default shell completions generated by mkGoBinary (all enabled). Kept as a
  # single source of truth that mkGoBinary merges caller overrides over, and
  # exposed so the merge contract can be unit-tested (bead pg2-beppe).
  completionDefaults = {
    bash = true;
    zsh = true;
    fish = true;
  };

  mkGoBinary =
    {
      name,
      src,
      description ? "",
      runtimeDeps ? [ ],
      # Which shell completions to generate. Merged OVER the all-true defaults
      # (see completionDefaults), so a partial set like `{ fish = false; }`
      # overrides only that shell instead of replacing the whole attrset and
      # leaving completions.bash/zsh undefined (bead pg2-beppe).
      completions ? { },
      manPage ? true,
      testDeps ? [ ],
      extraPostInstall ? "",
      # Go linker target for the version string (mkGoApp injects it).
      versionPath ? "main.Version",
      # gomod2nix engine (ADR 0008): mkGoBinary is a CLOSED arg set (no `...`)
      # and calls mkGoApp with an explicit attr list, so these must be threaded
      # explicitly or pn cannot reach mkGoApp. `gomod2nixToml` is required by
      # mkGoApp; pn passes it.
      gomod2nixToml,
      modRoot ? null,
      # Optional list of Go package import paths to build (buildGoApplication's
      # `subPackages`). Defaults to null → build every `main` in the module (the
      # historical behavior). Set it to pin the derivation's bin/ to specific
      # entrypoints when the module carries more than one `cmd/*` main.
      subPackages ? null,
    }:
    let
      # Resolve the requested completions by merging the caller's set over the
      # defaults, so a partial override keeps the untouched shells enabled
      # (bead pg2-beppe).
      completions' = completionDefaults // completions;
    in
    # Delegate to mkGoApp for the per-source version + gomod2nix build; this
    # opinionated wrapper only layers on the man-page / completion postInstall.
    mkGoApp (
      {
        pname = name;
        inherit
          src
          versionPath
          gomod2nixToml
          modRoot
          ;
        nativeBuildInputs = (lib.optional manPage pkgs.help2man) ++ [ pkgs.makeWrapper ];
        nativeCheckInputs = testDeps;
        postInstall = ''
          _try() {
            local label="$1"; shift
            local errfile
            errfile=$(mktemp)
            if ! "$@" 2> "$errfile"; then
              echo "WARN: $label failed:" >&2
              cat "$errfile" >&2
              rm -f "$errfile"
              return 1
            fi
            rm -f "$errfile"
            return 0
          }
          ${lib.optionalString manPage ''
            mkdir -p $out/share/man/man1
            _try "${name} help2man" \
              help2man --no-info --no-discard-stderr \
                --name="${description}" \
                --output=$out/share/man/man1/${name}.1 \
                $out/bin/${name} \
              || rm -f $out/share/man/man1/${name}.1
          ''}
          ${lib.optionalString completions'.bash ''
            mkdir -p $out/share/bash-completion/completions
            _try "${name} completion bash" \
              sh -c "$out/bin/${name} completion bash > $out/share/bash-completion/completions/${name}" \
              || rm -f $out/share/bash-completion/completions/${name}
          ''}
          ${lib.optionalString completions'.zsh ''
            mkdir -p $out/share/zsh/site-functions
            _try "${name} completion zsh" \
              sh -c "$out/bin/${name} completion zsh > $out/share/zsh/site-functions/_${name}" \
              || rm -f $out/share/zsh/site-functions/_${name}
          ''}
          ${lib.optionalString completions'.fish ''
            mkdir -p $out/share/fish/vendor_completions.d
            _try "${name} completion fish" \
              sh -c "$out/bin/${name} completion fish > $out/share/fish/vendor_completions.d/${name}.fish" \
              || rm -f $out/share/fish/vendor_completions.d/${name}.fish
          ''}
          ${lib.optionalString (runtimeDeps != [ ]) ''
            wrapProgram $out/bin/${name} --suffix PATH : ${lib.makeBinPath runtimeDeps}
          ''}
          ${extraPostInstall}
        '';
        # mkGoBinary installs a single exe at `$out/bin/${name}` by construction,
        # so mainProgram = name is unconditionally correct (fixes the getExe
        # mainProgram-warning class at the builder layer — see bead pg2-148y).
        meta = {
          inherit description;
          mainProgram = name;
        };
      }
      // lib.optionalAttrs (subPackages != null) { inherit subPackages; }
    );

  # mkGoApp — build a Go application via gomod2nix (buildGoApplication), keyed to
  # its OWN source rather than the whole flake. Unlike mkGoBinary (opinionated:
  # forces a man page + `<bin> completion` generation), this is a thin,
  # unopinionated wrapper that forwards every other buildGoApplication argument
  # untouched, so callers keep their bespoke postInstall / subPackages /
  # nativeBuildInputs / meta.
  #
  # Two halves (ADR 0006 + ADR 0008):
  #   1. `version` is derived from THIS package's own `src` digest, so it
  #      changes iff the package's files change — giving per-edit `nvd` /
  #      `--version` attribution AND isolation (a sibling package, or a docs
  #      commit, never rebuilds it).
  #   2. Dependencies are vendored as per-module content-addressed FODs read
  #      from a committed `gomod2nix.toml` beside `go.mod`. There is no
  #      `vendorHash` to bump and no monolithic vendor FOD to invalidate; first-
  #      party local `replace => ../sibling` modules are a native path dep read
  #      live from source. To add/bump a dep: `go get` + `go mod tidy` +
  #      `nix run github:nix-community/gomod2nix -- generate`, then commit the toml.
  #
  # Usage (ADR 0008 §"The pattern"). The committed `gomod2nix.toml` always sits
  # beside `go.mod`; the consumer never names it — mkGoApp derives `pwd` and
  # passes `modules = pwd + "/gomod2nix.toml"`.
  #
  #   Pattern A — single module at the package root (the common case):
  #     mkGoApp {
  #       pname = "<name>";
  #       src = lib.cleanSource ./.;   # go.mod + gomod2nix.toml at the root
  #       subPackages = [ "cmd/<name>" ];
  #       # NO modRoot. mkGoApp sets pwd = src.
  #     }
  #
  #   Pattern B — a local `replace => ../sibling` (pa-monitor, ccpool, pr-pool):
  #     mkGoApp {
  #       pname = "<name>";
  #       # Root src at the PARENT so the sibling is inside ONE store tree.
  #       src = lib.fileset.toSource {
  #         root = ./..;
  #         fileset = lib.fileset.unions [ ./. ../<sibling> ];
  #       };
  #       modRoot = "<name>";          # mkGoApp sets pwd = src + "/<name>"
  #       subPackages = [ "cmd/<name>" ];
  #     }
  #
  # The local-replace symlink in Pattern B resolves because `pwd` and the sibling
  # live in the same rooted store copy.
  mkGoApp =
    {
      pname,
      src,
      # Go linker target for the version string. Defaults to `main.Version` to
      # match mkGoBinary and the fleet convention (packages export
      # `var Version`), so a direct mkGoApp caller does not silently get a no-op
      # `-X main.version=` against code that declares `Version` (bead pg2-nc6vq).
      # Pass another symbol (e.g. "main.version") for a package that uses one.
      versionPath ? "main.Version",
      # Human-facing base; the per-source digest is appended for uniqueness.
      baseVersion ? "0.0.0",
      ldflags ? [ ],
      # Committed gomod2nix lockfile, conventionally ./gomod2nix.toml beside
      # go.mod (REQUIRED). mkGoApp resolves its location from `pwd`, so callers
      # pass the toml only to signal it is committed — its actual path is derived.
      gomod2nixToml,
      modRoot ? null,
      ...
    }@args:
    let
      # 8-char digest of the package's own (filtered) source tree via the shared
      # helper, so this digest changes iff a file included in `src` changes —
      # never for sibling packages. `src` may also be a list of paths (the helper
      # joins them). See ADR 0006.
      version = "${baseVersion}-${(import ./version.nix).mkSrcDigest src}";

      # `pwd` carries module/replace resolution: it is `src` in Pattern A and
      # `src + "/" + modRoot` in Pattern B (where the sibling replace resolves
      # within the same rooted store copy). `modRoot` stays in `forwarded` so
      # buildGoApplication uses it as the build working dir — it is intentionally
      # NOT stripped.
      pwd = if modRoot != null then src + "/" + modRoot else src;
      # Derive meta.mainProgram = baseNameOf (head subPackages) ONLY when exactly
      # one subPackage is built — then the installed exe name is known. For a null
      # or multi-entry subPackages we do not guess (bead pg2-148y). A caller's
      # explicit meta.mainProgram always wins via the merge below.
      derivedMainProgram =
        let
          sp = args.subPackages or null;
        in
        if sp != null && builtins.length sp == 1 then baseNameOf (builtins.head sp) else null;
      # `meta` is reassembled explicitly (default merged BENEATH args.meta so a
      # caller-supplied mainProgram wins), so strip it from `forwarded` to avoid
      # passing it twice into buildGoApplication.
      forwarded = builtins.removeAttrs args [
        "pname"
        "versionPath"
        "baseVersion"
        "ldflags"
        "version"
        "gomod2nixToml"
        "meta"
      ];
    in
    # `version` is DERIVED (baseVersion + source digest) and then stripped from
    # `forwarded`, so a caller-passed `version` was silently discarded — the open
    # `...` arg set hid the mistake that mkGoBinary (a closed arg set) rejects.
    # Fail loudly and name the right knob instead (bead pg2-zvt37).
    assert lib.assertMsg (!(args ? version))
      "mkGoApp: `version` is derived from baseVersion + the source digest and cannot be set directly; pass `baseVersion` instead.";
    # `gomod2nixToml` is required (the committed lockfile must exist beside
    # go.mod) but its location is derived from `pwd`, so it is asserted rather
    # than threaded by value.
    assert gomod2nixToml != null;
    pkgs.buildGoApplication (
      forwarded
      // {
        inherit pname version pwd;
        inherit (pkgs) go; # pin to our nixpkgs Go, not gomod2nix's
        modules = pwd + "/gomod2nix.toml";
        ldflags = ldflags ++ [ "-X ${versionPath}=${version}" ];
        # Default mainProgram merged BENEATH the caller's meta so an explicit
        # meta.mainProgram always wins (last-wins). No key added when nothing was
        # derived (multi-main / no subPackages) and the caller set no meta.
        meta =
          (lib.optionalAttrs (derivedMainProgram != null) { mainProgram = derivedMainProgram; })
          // (args.meta or { });
      }
    );

  # mkGoLint — run golangci-lint over a Go module OFFLINE, reusing gomod2nix's
  # vendored dependency env (ADR 0008). buildGoApplication's goConfigHook sets up
  # the read-only vendor tree and exports `GOFLAGS=-mod=vendor` BEFORE the build
  # phase, so golangci-lint resolves the full package graph with NO network — the
  # property a sandboxed `nix flake check` requires (bead pg2-6wly). A plain
  # git-hooks hook with an empty module cache + `-mod=mod` instead tries to fetch
  # deps from proxy.golang.org and fails in the no-network sandbox.
  #
  # We REPLACE the build phase with the lint pass: neither recompiling the binary
  # nor re-running `go test` (that is <module>-go-tests' job). This also confines
  # golangci-lint / .golangci.yml input churn to this derivation rather than the
  # package build (ADR 0006).
  #
  #   config: path to the golangci-lint config (the repo-root .golangci.yml). It
  #   lives OUTSIDE the module `src`, so it MUST be passed explicitly and becomes a
  #   derivation input — otherwise golangci-lint falls back to its defaults and
  #   loses the config's errcheck fmt.Fprint* exclusions.
  mkGoLint =
    {
      src,
      # Committed gomod2nix lockfile beside go.mod (REQUIRED; its path is derived
      # from `pwd`, mirroring mkGoApp — passed only to signal it is committed).
      gomod2nixToml,
      config,
      pname ? "golangci-lint",
      modRoot ? null,
    }:
    let
      version = "0.0.0-${(import ./version.nix).mkSrcDigest src}";
      pwd = if modRoot != null then src + "/" + modRoot else src;
    in
    assert gomod2nixToml != null;
    pkgs.buildGoApplication {
      inherit
        pname
        version
        src
        pwd
        ;
      inherit (pkgs) go; # pin to our nixpkgs Go, matching mkGoApp
      modules = pwd + "/gomod2nix.toml";
      nativeBuildInputs = [ pkgs.golangci-lint ];
      # Skip `go test`; linting only. (<module>-go-tests runs the suite.)
      doCheck = false;
      # goConfigHook (vendor setup + GOFLAGS=-mod=vendor) has already run by the
      # time buildPhase starts, so replace the go build with the lint pass.
      buildPhase = ''
        runHook preBuild
        # Sandbox $HOME (/homeless-shelter) is read-only; give golangci-lint and
        # the Go build cache writable scratch dirs.
        export HOME="$TMPDIR" \
               GOCACHE="$TMPDIR/go-build" \
               GOLANGCI_LINT_CACHE="$TMPDIR/golangci-lint"
        golangci-lint run --config ${config} ./...
        runHook postBuild
      '';
      installPhase = "touch $out";
      meta.description = "golangci-lint (offline, gomod2nix vendor env): ${pname}";
    };
}
