# mkGoBuilders — Go-equivalent of mkBashBuilders. Provides:
#   - mkGoApp: build a Go app via gomod2nix (buildGoApplication), keyed to its
#     own source digest (ADR 0006) so editing source gives per-edit `--version`
#     attribution without rebuilding sibling packages. Dependencies are vendored
#     as per-module content-addressed FODs read from a committed `gomod2nix.toml`
#     (ADR 0008), so there is no `vendorHash` to bump and no whole-repo FOD to
#     invalidate.
#   - mkGoBinary: opinionated wrapper over mkGoApp that also generates a man
#     page (help2man) and shell completions.
{
  pkgs,
  lib ? pkgs.lib,
  # `self` is accepted for signature parity with mkBashBuilders but unused here.
  ...
}:
assert
  pkgs ? buildGoApplication
  || throw ''
    mkGoBuilders requires pkgs.buildGoApplication (gomod2nix's overlay).
    Either:
      - Import phillipgreenii-nix-base.flakeModules.gomod2nix-overlay and
        apply self.overlays.gomod2nix to your pkgs, OR
      - Declare inputs.gomod2nix directly and apply
        inputs.gomod2nix.overlays.default to your pkgs.
  '';
rec {
  # Default shell completions generated by mkGoBinary (all enabled). Kept as a
  # single source of truth that mkGoBinary merges caller overrides over, and
  # exposed so the merge contract can be unit-tested (bead pg2-beppe).
  completionDefaults = {
    bash = true;
    zsh = true;
    fish = true;
  };

  mkGoBinary =
    {
      name,
      src,
      description ? "",
      runtimeDeps ? [ ],
      # Which shell completions to generate. Merged OVER the all-true defaults
      # (see completionDefaults), so a partial set like `{ fish = false; }`
      # overrides only that shell instead of replacing the whole attrset and
      # leaving completions.bash/zsh undefined (bead pg2-beppe).
      completions ? { },
      manPage ? true,
      testDeps ? [ ],
      extraPostInstall ? "",
      # Go linker target for the version string (mkGoApp injects it).
      versionPath ? "main.Version",
      # Human-facing base version. mkGoApp derives
      # `version = "${baseVersion}-${srcDigest}"`, so a release build reads
      # `2.1.0-<8hex>` instead of `0.0.0-<8hex>`. This is NOT an ADR 0006
      # exception: the per-source digest is ALWAYS appended, so the version is
      # never a bare `2.1.0` and never carries the repo git rev. It mirrors the
      # `baseVersion` argument ADR 0011 already added to mkBashScript "as a new
      # argument defaulting to 0.0.0" — mkGoBinary was the outlier that could not
      # reach mkGoApp's long-standing `baseVersion` because this arg set is
      # closed (bead tc-5lxy.26).
      #
      # CONSUMER CONSTRAINT — the producer CANNOT enforce this, so it is stated
      # here: the value MUST be derived from SOURCE CONTENT (e.g. a committed
      # `VERSION` file read with `builtins.readFile ./VERSION`). A value derived
      # from `self.rev` / `self.ref` / `self.dirtyRev` reintroduces exactly the
      # per-commit derivation churn ADR 0006 exists to remove: `version` — and
      # therefore the drvPath — would change on every commit, rebuilding the
      # package for edits it does not contain.
      baseVersion ? "0.0.0",
      # Extra Go linker flags. mkGoApp appends its own
      # `-X <versionPath>=<version>` after these, so the version injection is
      # never lost. Typical use: [ "-s -w" ] to drop the symbol table and DWARF.
      ldflags ? [ ],
      # Extra build-time environment (stdenv's `env`). Note that
      # `env.CGO_ENABLED = <n>` — the static-binary spelling buildGoModule
      # consumers already write — is HOISTED by mkGoApp onto the top-level
      # attribute gomod2nix reads; see the note in mkGoApp for why that shim
      # exists.
      env ? { },
      # Extra package metadata, merged OVER mkGoBinary's own
      # `{ description, mainProgram }` so a caller may add homepage / license /
      # platforms (and override either default) without losing them.
      meta ? { },
      # gomod2nix engine (ADR 0008): mkGoBinary is a CLOSED arg set (no `...`)
      # and calls mkGoApp with an explicit attr list, so these must be threaded
      # explicitly or pn cannot reach mkGoApp. `gomod2nixToml` is required by
      # mkGoApp; pn passes it.
      gomod2nixToml,
      modRoot ? null,
      # Optional list of Go package import paths to build (buildGoApplication's
      # `subPackages`). Defaults to null → build every `main` in the module (the
      # historical behavior). Set it to pin the derivation's bin/ to specific
      # entrypoints when the module carries more than one `cmd/*` main.
      subPackages ? null,
    }:
    let
      # Resolve the requested completions by merging the caller's set over the
      # defaults, so a partial override keeps the untouched shells enabled
      # (bead pg2-beppe).
      completions' = completionDefaults // completions;
      # Keep `meta` reachable under an unambiguous name inside the (non-rec)
      # attrset literal below, where the key `meta` is also being defined.
      extraMeta = meta;
    in
    # Delegate to mkGoApp for the per-source version + gomod2nix build; this
    # opinionated wrapper only layers on the man-page / completion postInstall.
    mkGoApp (
      {
        pname = name;
        inherit
          src
          versionPath
          baseVersion
          ldflags
          gomod2nixToml
          modRoot
          ;
        nativeBuildInputs = (lib.optional manPage pkgs.help2man) ++ [ pkgs.makeWrapper ];
        nativeCheckInputs = testDeps;
        postInstall = ''
          _try() {
            local label="$1"; shift
            local errfile
            errfile=$(mktemp)
            if ! "$@" 2> "$errfile"; then
              echo "WARN: $label failed:" >&2
              cat "$errfile" >&2
              rm -f "$errfile"
              return 1
            fi
            rm -f "$errfile"
            return 0
          }
          ${lib.optionalString manPage ''
            mkdir -p $out/share/man/man1
            _try "${name} help2man" \
              help2man --no-info --no-discard-stderr \
                --name="${description}" \
                --output=$out/share/man/man1/${name}.1 \
                $out/bin/${name} \
              || rm -f $out/share/man/man1/${name}.1
          ''}
          ${lib.optionalString completions'.bash ''
            mkdir -p $out/share/bash-completion/completions
            _try "${name} completion bash" \
              sh -c "$out/bin/${name} completion bash > $out/share/bash-completion/completions/${name}" \
              || rm -f $out/share/bash-completion/completions/${name}
          ''}
          ${lib.optionalString completions'.zsh ''
            mkdir -p $out/share/zsh/site-functions
            _try "${name} completion zsh" \
              sh -c "$out/bin/${name} completion zsh > $out/share/zsh/site-functions/_${name}" \
              || rm -f $out/share/zsh/site-functions/_${name}
          ''}
          ${lib.optionalString completions'.fish ''
            mkdir -p $out/share/fish/vendor_completions.d
            _try "${name} completion fish" \
              sh -c "$out/bin/${name} completion fish > $out/share/fish/vendor_completions.d/${name}.fish" \
              || rm -f $out/share/fish/vendor_completions.d/${name}.fish
          ''}
          ${lib.optionalString (runtimeDeps != [ ]) ''
            wrapProgram $out/bin/${name} --suffix PATH : ${lib.makeBinPath runtimeDeps}
          ''}
          ${extraPostInstall}
        '';
        # mkGoBinary installs a single exe at `$out/bin/${name}` by construction,
        # so mainProgram = name is unconditionally correct (fixes the getExe
        # mainProgram-warning class at the builder layer — see bead pg2-148y).
        # The caller's `meta` is merged OVER these defaults (last-wins), so
        # homepage/license/platforms are additive and either default is
        # overridable.
        meta = {
          inherit description;
          mainProgram = name;
        }
        // extraMeta;
      }
      // lib.optionalAttrs (subPackages != null) { inherit subPackages; }
      # Omit `env` entirely when the caller passed none, so every existing
      # mkGoBinary consumer's derivation hash is unchanged by this widening.
      // lib.optionalAttrs (env != { }) { inherit env; }
    );

  # mkGoApp — build a Go application via gomod2nix (buildGoApplication), keyed to
  # its OWN source rather than the whole flake. Unlike mkGoBinary (opinionated:
  # forces a man page + `<bin> completion` generation), this is a thin,
  # unopinionated wrapper that forwards every other buildGoApplication argument
  # untouched, so callers keep their bespoke postInstall / subPackages /
  # nativeBuildInputs / meta.
  #
  # Two halves (ADR 0006 + ADR 0008):
  #   1. `version` is derived from THIS package's own `src` digest, so it
  #      changes iff the package's files change — giving per-edit `nvd` /
  #      `--version` attribution AND isolation (a sibling package, or a docs
  #      commit, never rebuilds it).
  #   2. Dependencies are vendored as per-module content-addressed FODs read
  #      from a committed `gomod2nix.toml` beside `go.mod`. There is no
  #      `vendorHash` to bump and no monolithic vendor FOD to invalidate; first-
  #      party local `replace => ../sibling` modules are a native path dep read
  #      live from source. To add/bump a dep: `go get` + `go mod tidy` +
  #      `nix run github:nix-community/gomod2nix -- generate`, then commit the toml.
  #
  # Usage (ADR 0008 §"The pattern"). The committed `gomod2nix.toml` always sits
  # beside `go.mod`; the consumer never names it — mkGoApp derives `pwd` and
  # passes `modules = pwd + "/gomod2nix.toml"`.
  #
  #   Pattern A — single module at the package root (the common case):
  #     mkGoApp {
  #       pname = "<name>";
  #       src = lib.cleanSource ./.;   # go.mod + gomod2nix.toml at the root
  #       subPackages = [ "cmd/<name>" ];
  #       # NO modRoot. mkGoApp sets pwd = src.
  #     }
  #
  #   Pattern B — a local `replace => ../sibling` (pa-monitor, ccpool, pr-pool):
  #     mkGoApp {
  #       pname = "<name>";
  #       # Root src at the PARENT so the sibling is inside ONE store tree.
  #       src = lib.fileset.toSource {
  #         root = ./..;
  #         fileset = lib.fileset.unions [ ./. ../<sibling> ];
  #       };
  #       modRoot = "<name>";          # mkGoApp sets pwd = src + "/<name>"
  #       subPackages = [ "cmd/<name>" ];
  #     }
  #
  # The local-replace symlink in Pattern B resolves because `pwd` and the sibling
  # live in the same rooted store copy.
  mkGoApp =
    {
      pname,
      src,
      # Go linker target for the version string. Defaults to `main.Version` to
      # match mkGoBinary and the fleet convention (packages export
      # `var Version`), so a direct mkGoApp caller does not silently get a no-op
      # `-X main.version=` against code that declares `Version` (bead pg2-nc6vq).
      # Pass another symbol (e.g. "main.version") for a package that uses one.
      versionPath ? "main.Version",
      # Human-facing base; the per-source digest is appended for uniqueness.
      # CONSUMER CONSTRAINT (unenforceable here, so stated): this MUST be
      # SOURCE-CONTENT derived — a committed `VERSION` file, not `self.rev` /
      # `self.ref` / `self.dirtyRev`, which would put the repo git rev back into
      # the derivation version and undo ADR 0006. See mkGoBinary's copy of this
      # note for the full rationale.
      baseVersion ? "0.0.0",
      # Caller's Go linker flags; the `-X ${versionPath}=${version}` injection is
      # appended AFTER these, so it can never be lost.
      ldflags ? [ ],
      # Committed gomod2nix lockfile, conventionally ./gomod2nix.toml beside
      # go.mod (REQUIRED). mkGoApp resolves its location from `pwd`, so callers
      # pass the toml only to signal it is committed — its actual path is derived.
      gomod2nixToml,
      modRoot ? null,
      ...
    }@args:
    let
      # 8-char digest of the package's own (filtered) source tree via the shared
      # helper, so this digest changes iff a file included in `src` changes —
      # never for sibling packages. `src` may also be a list of paths (the helper
      # joins them). See ADR 0006.
      version = "${baseVersion}-${(import ./version.nix).mkSrcDigest src}";

      # `pwd` carries module/replace resolution: it is `src` in Pattern A and
      # `src + "/" + modRoot` in Pattern B (where the sibling replace resolves
      # within the same rooted store copy). `modRoot` stays in `forwarded` so
      # buildGoApplication uses it as the build working dir — it is intentionally
      # NOT stripped.
      pwd = if modRoot != null then src + "/" + modRoot else src;
      # Derive meta.mainProgram = baseNameOf (head subPackages) ONLY when exactly
      # one subPackage is built — then the installed exe name is known. For a null
      # or multi-entry subPackages we do not guess (bead pg2-148y). A caller's
      # explicit meta.mainProgram always wins via the merge below.
      derivedMainProgram =
        let
          sp = args.subPackages or null;
        in
        if sp != null && builtins.length sp == 1 then baseNameOf (builtins.head sp) else null;
      # gomod2nix's buildGoApplication sets `CGO_ENABLED` as a TOP-LEVEL
      # derivation attribute (`CGO_ENABLED = attrs.CGO_ENABLED or
      # go.CGO_ENABLED;`, builder/default.nix) and sets it UNCONDITIONALLY, so a
      # caller's `env.CGO_ENABLED` collides with it and stdenv aborts at eval:
      #   error: The `env` attribute set cannot contain any attributes passed to
      #   derivation. The following attributes are overlapping:
      #     - CGO_ENABLED: in `env`: 0; in derivation arguments: 1
      # `env.CGO_ENABLED = 0` is nonetheless the spelling every buildGoModule
      # consumer already writes for a static binary (e.g. mobilecombackup's
      # flake.nix), and silently dropping it yields a dynamically linked binary
      # rather than a loud failure. So accept that spelling and HOIST it onto the
      # attribute the gomod2nix engine actually reads; the rest of `env` is
      # forwarded untouched, and an explicit top-level `CGO_ENABLED` still wins
      # (bead tc-5lxy.26).
      callerEnv = args.env or { };
      hoistedCgo = lib.optionalAttrs (callerEnv ? CGO_ENABLED) {
        CGO_ENABLED = args.CGO_ENABLED or callerEnv.CGO_ENABLED;
      };
      envRest = builtins.removeAttrs callerEnv [ "CGO_ENABLED" ];
      # `meta` is reassembled explicitly (default merged BENEATH args.meta so a
      # caller-supplied mainProgram wins), so strip it from `forwarded` to avoid
      # passing it twice into buildGoApplication. `env` is likewise reassembled
      # (see the CGO_ENABLED hoist above) and so is stripped here too.
      forwarded = builtins.removeAttrs args [
        "pname"
        "versionPath"
        "baseVersion"
        "ldflags"
        "version"
        "gomod2nixToml"
        "meta"
        "env"
      ];
    in
    # `version` is DERIVED (baseVersion + source digest) and then stripped from
    # `forwarded`, so a caller-passed `version` was silently discarded — the open
    # `...` arg set hid the mistake that mkGoBinary (a closed arg set) rejects.
    # Fail loudly and name the right knob instead (bead pg2-zvt37).
    assert lib.assertMsg (!(args ? version))
      "mkGoApp: `version` is derived from baseVersion + the source digest and cannot be set directly; pass `baseVersion` instead.";
    # `gomod2nixToml` is required (the committed lockfile must exist beside
    # go.mod) but its location is derived from `pwd`, so it is asserted rather
    # than threaded by value.
    assert gomod2nixToml != null;
    pkgs.buildGoApplication (
      forwarded
      // {
        inherit pname version pwd;
        inherit (pkgs) go; # pin to our nixpkgs Go, not gomod2nix's
        modules = pwd + "/gomod2nix.toml";
        ldflags = ldflags ++ [ "-X ${versionPath}=${version}" ];
        # Default mainProgram merged BENEATH the caller's meta so an explicit
        # meta.mainProgram always wins (last-wins). No key added when nothing was
        # derived (multi-main / no subPackages) and the caller set no meta.
        meta =
          (lib.optionalAttrs (derivedMainProgram != null) { mainProgram = derivedMainProgram; })
          // (args.meta or { });
      }
      // hoistedCgo
      # Re-add `env` only when something other than CGO_ENABLED was in it, so
      # callers that pass no `env` (or only `env.CGO_ENABLED`) keep a derivation
      # with no `env` attribute at all — hash-neutral for every existing caller.
      // lib.optionalAttrs (envRest != { }) { env = envRest; }
    );

  # mkGoLint — run golangci-lint over a Go module OFFLINE, reusing gomod2nix's
  # vendored dependency env (ADR 0008). buildGoApplication's goConfigHook sets up
  # the read-only vendor tree and exports `GOFLAGS=-mod=vendor` BEFORE the build
  # phase, so golangci-lint resolves the full package graph with NO network — the
  # property a sandboxed `nix flake check` requires (bead pg2-6wly). A plain
  # git-hooks hook with an empty module cache + `-mod=mod` instead tries to fetch
  # deps from proxy.golang.org and fails in the no-network sandbox.
  #
  # We REPLACE the build phase with the lint pass: neither recompiling the binary
  # nor re-running `go test` (that is <module>-go-tests' job). This also confines
  # golangci-lint / .golangci.yml input churn to this derivation rather than the
  # package build (ADR 0006).
  #
  #   config: path to the golangci-lint config (the repo-root .golangci.yml). It
  #   lives OUTSIDE the module `src`, so it MUST be passed explicitly and becomes a
  #   derivation input — otherwise golangci-lint falls back to its defaults and
  #   loses the config's errcheck fmt.Fprint* exclusions.
  mkGoLint =
    {
      src,
      # Committed gomod2nix lockfile beside go.mod (REQUIRED; its path is derived
      # from `pwd`, mirroring mkGoApp — passed only to signal it is committed).
      gomod2nixToml,
      config,
      pname ? "golangci-lint",
      modRoot ? null,
    }:
    let
      version = "0.0.0-${(import ./version.nix).mkSrcDigest src}";
      pwd = if modRoot != null then src + "/" + modRoot else src;
    in
    assert gomod2nixToml != null;
    pkgs.buildGoApplication (
      {
        inherit
          pname
          version
          src
          pwd
          ;
        inherit (pkgs) go; # pin to our nixpkgs Go, matching mkGoApp
        modules = pwd + "/gomod2nix.toml";
        nativeBuildInputs = [ pkgs.golangci-lint ];
        # Skip `go test`; linting only. (<module>-go-tests runs the suite.)
        doCheck = false;
        # goConfigHook (vendor setup + GOFLAGS=-mod=vendor) has already run by the
        # time buildPhase starts, so replace the go build with the lint pass.
        buildPhase = ''
          runHook preBuild
          # Sandbox $HOME (/homeless-shelter) is read-only; give golangci-lint and
          # the Go build cache writable scratch dirs.
          export HOME="$TMPDIR" \
                 GOCACHE="$TMPDIR/go-build" \
                 GOLANGCI_LINT_CACHE="$TMPDIR/golangci-lint"
          golangci-lint run --config ${config} ./...
          runHook postBuild
        '';
        installPhase = "touch $out";
        meta.description = "golangci-lint (offline, gomod2nix vendor env): ${pname}";
      }
      # Forward modRoot so goConfigHook cd's into the module subdir instead of the
      # fileset root. For Pattern-B modules (local `replace => ../sibling`) the
      # fileset root is the PARENT (no go.mod), so without this golangci-lint fails
      # with "directory prefix . does not contain main module". `pwd` (eval-time
      # store path for gomod2nix's replace resolution) and `modRoot` (build-time
      # relative cd) are orthogonal — this mirrors the proven mkGoApp path. The
      # optionalAttrs guard omits modRoot for Pattern-A callers (modRoot == null),
      # leaving their derivation hash unchanged (bead pg2-sjxhy).
      // lib.optionalAttrs (modRoot != null) { inherit modRoot; }
    );

  # mkGoTest — run the FULL `go test ./...` suite for a Go module OFFLINE,
  # reusing gomod2nix's vendored dep env (ADR 0008), exactly like mkGoLint.
  # This is the real test gate: it MUST NOT set `subPackages` — that scopes
  # gomod2nix's check hook (getGoDirs, go-config-hook.sh:37) to a single
  # entrypoint and silently skips the internal/* suite (bead pg2-2jqj0). We run
  # `go test ./...` in buildPhase (not via buildGoApplication's subPackage-scoped
  # check phase) so coverage is explicit and independent of the package's own
  # subPackages pin. `go vet` runs (the `go test` default) — intentionally
  # stricter than gomod2nix's -vet=off check hook, matching a dev's `go test`.
  #
  #   testDeps: tools the suite shells out to at test time (e.g. git, nix).
  #     Placed on nativeBuildInputs so they are on PATH during the sandboxed run.
  #   testFlags: extra flags for `go test` (e.g. [ "-count=1" ]).
  mkGoTest =
    {
      src,
      # Committed gomod2nix lockfile beside go.mod (REQUIRED; path derived from
      # pwd, mirroring mkGoApp/mkGoLint — passed only to signal it is committed).
      gomod2nixToml,
      pname ? "go-tests",
      modRoot ? null,
      testDeps ? [ ],
      testFlags ? [ ],
    }:
    let
      version = "0.0.0-${(import ./version.nix).mkSrcDigest src}";
      pwd = if modRoot != null then src + "/" + modRoot else src;
    in
    assert gomod2nixToml != null;
    pkgs.buildGoApplication (
      {
        inherit
          pname
          version
          src
          pwd
          ;
        inherit (pkgs) go; # pin to our nixpkgs Go, matching mkGoApp/mkGoLint
        modules = pwd + "/gomod2nix.toml";
        nativeBuildInputs = testDeps;
        # Deliberately NO `subPackages`: the whole point of this builder.
        doCheck = false;
        # goConfigHook (vendor setup + GOFLAGS=-mod=vendor) has already run by the
        # time buildPhase starts, so replace the go build with the full test pass.
        buildPhase = ''
          runHook preBuild
          # Sandbox $HOME (/homeless-shelter) is read-only; give the Go build+test
          # cache writable scratch. GOFLAGS=-mod=vendor comes from goConfigHook.
          export HOME="$TMPDIR" \
                 GOCACHE="$TMPDIR/go-build"
          # Mirror gomod2nix's goCheckHook: drop -trimpath for the test run so
          # tests resolving assets via runtime.Caller/source paths behave the same
          # as a developer's `go test ./...`. Safe: the $out (touch) has no binary.
          export GOFLAGS=''${GOFLAGS//-trimpath/}
          go test ${lib.escapeShellArgs testFlags} ./...
          runHook postBuild
        '';
        installPhase = "touch $out";
        meta.description = "go test ./... (offline, gomod2nix vendor env): ${pname}";
      }
      # Forward modRoot for Pattern-B modules — identical fix and rationale as
      # mkGoLint above; optionalAttrs keeps Pattern-A callers' derivation hash
      # unchanged (bead pg2-sjxhy).
      // lib.optionalAttrs (modRoot != null) { inherit modRoot; }
    );
}
