// internal/workspace/doctor_checks_hookbundle_test.go
package workspace

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/phillipgreenii/nix-repo-base/modules/pn/internal/exec"
)

const hbDoctorStub = "#!/bin/sh\n# managed-by: pg-hooks\nexit 0\n"

// hbDoctorWorkspace wraps the hbRepo fixture in a one-repo workspace named
// "repo". declared adds the pn-workspace.toml entry that runs
// install-pre-commit-hooks (what makes a repo "declared").
func hbDoctorWorkspace(t *testing.T, declared bool) (*Workspace, string) {
	t.Helper()
	dir := hbRepo(t)
	rc := RepoConfig{URL: "git@github.com:o/repo.git", Branch: "main"}
	if declared {
		rc.Hooks = []EventHook{{
			When: []string{"post-clone", "post-rebase"},
			Run:  []string{"{nix_run install-pre-commit-hooks}"},
		}}
	}
	ws := &Workspace{
		root: filepath.Dir(dir), runner: exec.NewFakeRunner(),
		config: &WorkspaceConfig{Repos: map[string]RepoConfig{"repo": rc}},
	}
	return ws, dir
}

// hbWriteStages gives the fake bundle the stages.json the installer reads.
func hbWriteStages(t *testing.T, pg string, stages ...string) {
	t.Helper()
	var parts []string
	for _, s := range stages {
		parts = append(parts, `"`+s+`": [{"id": "x", "reason": "x"}]`)
	}
	writeFile(t, filepath.Join(pg, "gen-1", "bundle", "stages.json"), "{"+strings.Join(parts, ",")+"}")
}

func hbWriteStub(t *testing.T, dir, stage, content string, mode os.FileMode) {
	t.Helper()
	hooks := filepath.Join(runGitT(t, dir, "rev-parse", "--path-format=absolute", "--git-common-dir"), "hooks")
	mustMkdir(t, hooks)
	p := filepath.Join(hooks, stage)
	if err := os.WriteFile(p, []byte(content), mode); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(p, mode); err != nil {
		t.Fatal(err)
	}
}

// hbGoodInstall lays down a complete, healthy install: bundle, stages.json
// (pre-commit and pre-push) and a marked executable stub for each.
func hbGoodInstall(t *testing.T, dir string) string {
	t.Helper()
	pg := writeFakeBundle(t, dir, hbBundleOpts{})
	hbWriteStages(t, pg, "pre-commit", "pre-push")
	hbWriteStub(t, dir, "pre-commit", hbDoctorStub, 0o755)
	hbWriteStub(t, dir, "pre-push", hbDoctorStub, 0o755)
	return pg
}

func hbRunLive(ws *Workspace) []Finding {
	return ws.checkPreCommitHookLive(context.Background(), &doctorEnv{ws: ws, mode: "primary"})
}

// hbWantError asserts exactly the findings for repo "repo" are hard errors
// (not Skipped) and that one of them mentions msg and one carries manual.
func hbWantError(t *testing.T, fs []Finding, msg, manual string) {
	t.Helper()
	if len(fs) == 0 {
		t.Fatalf("expected a finding mentioning %q, got none", msg)
	}
	var gotMsg, gotManual bool
	for _, f := range fs {
		if f.CheckID != "pre-commit-hook-live" || f.Repo != "repo" || f.Severity != SevError || f.Skipped {
			t.Errorf("a bundle finding must be a non-skipped pre-commit-hook-live error for repo; got %+v", f)
		}
		if !strings.HasPrefix(f.Message, "pg-hooks: ") {
			t.Errorf("message must start with pg-hooks: %q", f.Message)
		}
		gotMsg = gotMsg || strings.Contains(f.Message, msg)
		gotManual = gotManual || strings.Contains(f.Manual, manual)
	}
	if !gotMsg {
		t.Errorf("no finding message contains %q: %+v", msg, fs)
	}
	if !gotManual {
		t.Errorf("no finding fix line contains %q: %+v", manual, fs)
	}
}

func TestCheckPreCommitHookLive_Bundle_HealthyInstallIsClean(t *testing.T) {
	ws, dir := hbDoctorWorkspace(t, true)
	hbGoodInstall(t, dir)
	if fs := hbRunLive(ws); len(fs) != 0 {
		t.Fatalf("a healthy bundle install must produce no finding; got %+v", fs)
	}
}

func TestCheckPreCommitHookLive_Bundle_MissingPointerIsError(t *testing.T) {
	ws, dir := hbDoctorWorkspace(t, true)
	fs := hbRunLive(ws)
	hbWantError(t, fs, "no hook bundle", "(cd "+dir+" && nix run .#install-pre-commit-hooks)")
}

func TestCheckPreCommitHookLive_Bundle_ForeignStubIsError(t *testing.T) {
	ws, dir := hbDoctorWorkspace(t, true)
	hbGoodInstall(t, dir)
	hbWriteStub(t, dir, "pre-push", "#!/bin/sh\necho mine\n", 0o755)
	fs := hbRunLive(ws)
	hbWantError(t, fs, "pre-push (foreign file, no pg-hooks marker)", "install-pre-commit-hooks")
	if strings.Contains(fs[0].Message, "pre-commit (") {
		t.Errorf("the healthy pre-commit stub must not be named: %q", fs[0].Message)
	}
}

func TestCheckPreCommitHookLive_Bundle_LegacyPrekStubMissesMarker(t *testing.T) {
	ws, dir := hbDoctorWorkspace(t, true)
	hbGoodInstall(t, dir)
	hbWriteStub(t, dir, "pre-commit", "#!/usr/bin/env bash\n# File generated by prek\nexit 0\n", 0o755)
	hbWantError(t, hbRunLive(ws), "pre-commit (legacy prek stub, no pg-hooks marker)", "install-pre-commit-hooks")
}

func TestCheckPreCommitHookLive_Bundle_MissingAndNonExecutableStubs(t *testing.T) {
	ws, dir := hbDoctorWorkspace(t, true)
	hbGoodInstall(t, dir)
	hooks := filepath.Join(runGitT(t, dir, "rev-parse", "--path-format=absolute", "--git-common-dir"), "hooks")
	if err := os.Remove(filepath.Join(hooks, "pre-push")); err != nil {
		t.Fatal(err)
	}
	hbWriteStub(t, dir, "pre-commit", hbDoctorStub, 0o644)
	fs := hbRunLive(ws)
	hbWantError(t, fs, "pre-push (missing)", "install-pre-commit-hooks")
	hbWantError(t, fs, "pre-commit (not executable)", "install-pre-commit-hooks")
}

func TestCheckPreCommitHookLive_Bundle_DanglingBundleIsError(t *testing.T) {
	ws, dir := hbDoctorWorkspace(t, true)
	pg := hbGoodInstall(t, dir)
	if err := os.RemoveAll(filepath.Join(pg, "gen-1", "bundle")); err != nil {
		t.Fatal(err)
	}
	// The installer's reinstall line, when present, is the fix line.
	writeFile(t, filepath.Join(pg, "reinstall"), "(cd /x && nix run .#install-pre-commit-hooks)\n")
	hbWantError(t, hbRunLive(ws), "GC root dangles", "(cd /x && nix run .#install-pre-commit-hooks)")
}

func TestCheckPreCommitHookLive_Bundle_BrokenBundleIsError(t *testing.T) {
	ws, dir := hbDoctorWorkspace(t, true)
	pg := hbGoodInstall(t, dir)
	if err := os.Chmod(filepath.Join(pg, "gen-1", "bundle", "bin", "prek"), 0o644); err != nil {
		t.Fatal(err)
	}
	hbWantError(t, hbRunLive(ws), "broken", "install-pre-commit-hooks")
}

func TestCheckPreCommitHookLive_Bundle_InvalidPointerIsError(t *testing.T) {
	ws, dir := hbDoctorWorkspace(t, true)
	pg := hbGoodInstall(t, dir)
	writeFile(t, filepath.Join(pg, "current"), "not-a-gen\n")
	// An old config alongside the invalid pointer changes nothing.
	writeFile(t, filepath.Join(dir, ".pre-commit-config.yaml"), "repos: []\n")
	hbWantError(t, hbRunLive(ws), "broken", "install-pre-commit-hooks")
}

func TestCheckPreCommitHookLive_Bundle_RelocatedCloneIsError(t *testing.T) {
	ws, dir := hbDoctorWorkspace(t, true)
	pg := writeFakeBundle(t, dir, hbBundleOpts{ClonePath: "/elsewhere/old/.git"})
	hbWriteStages(t, pg, "pre-commit")
	hbWriteStub(t, dir, "pre-commit", hbDoctorStub, 0o755)
	hbWantError(t, hbRunLive(ws), "moved from /elsewhere/old/.git", "install-pre-commit-hooks")
}

func TestCheckPreCommitHookLive_Bundle_UnreachableHooksPathIsError(t *testing.T) {
	ws, dir := hbDoctorWorkspace(t, true)
	hbGoodInstall(t, dir)
	runGitT(t, dir, "config", "--local", "core.hooksPath", ".githooks-nowhere")
	fs := hbRunLive(ws)
	hbWantError(t, fs, "core.hooksPath=.githooks-nowhere", "config --local --unset core.hooksPath")
	for _, f := range fs {
		if strings.Contains(f.Message, "does not run hooks") && !strings.HasPrefix(f.Manual, "operator:") {
			t.Errorf("the unreachable fix line is operator-only: %q", f.Manual)
		}
	}
}

func TestCheckPreCommitHookLive_Bundle_UnreachableWithoutPointerIsError(t *testing.T) {
	ws, dir := hbDoctorWorkspace(t, true)
	runGitT(t, dir, "config", "--local", "core.hooksPath", "/nonexistent/hooks")
	fs := hbRunLive(ws)
	hbWantError(t, fs, "no hook bundle", "install-pre-commit-hooks")
	hbWantError(t, fs, "core.hooksPath=/nonexistent/hooks", "--unset core.hooksPath")
}

func TestCheckPreCommitHookLive_Bundle_UndeclaredRepoHasNoFinding(t *testing.T) {
	ws, dir := hbDoctorWorkspace(t, false)
	// Broken in every way a declared repo would be flagged for.
	pg := hbGoodInstall(t, dir)
	hbWriteStub(t, dir, "pre-push", "#!/bin/sh\necho mine\n", 0o755)
	writeFile(t, filepath.Join(pg, "current"), "garbage\n")
	if fs := hbRunLive(ws); len(fs) != 0 {
		t.Fatalf("an undeclared repo must produce no finding; got %+v", fs)
	}
}

func TestCheckRuffPin_ReadsBundlePrekConfig(t *testing.T) {
	ws, dir := hbDoctorWorkspace(t, true)
	pg := hbGoodInstall(t, dir)
	writeRuffPackage(t, dir, "core", "ruff==0.15.13")
	// Only the bundle holds the config: there is no .pre-commit-config.yaml.
	writeFile(t, filepath.Join(pg, "gen-1", "bundle", "prek-config.json"), ruffHookConfig("0.15.14"))

	fs := ws.checkRuffPin(context.Background(), &doctorEnv{ws: ws, mode: "primary"})
	f := findingByID(t, fs, "ruff-pin-drift")
	if f.Repo != "repo" || !strings.Contains(f.Message, "0.15.14") {
		t.Errorf("drift must be judged against the bundle's ruff 0.15.14: %+v", f)
	}

	// A matching pin is clean.
	writeRuffPackage(t, dir, "core", "ruff==0.15.14")
	if fs := ws.checkRuffPin(context.Background(), &doctorEnv{ws: ws, mode: "primary"}); len(fs) != 0 {
		t.Fatalf("a pin matching the bundle's ruff must be clean; got %+v", fs)
	}
}
