// internal/workspace/doctor_checks_hookbundle.go
package workspace

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// hookStubMarker is the line that marks a stub as owned by pg-hooks
// (modules/pg-hooks/stub.sh.in); hookLegacyStubMarker is what prek's own stub
// carries, which the installer replaces.
const (
	hookStubMarker       = "# managed-by: pg-hooks"
	hookLegacyStubMarker = "File generated by prek"
)

// installHookDeclared reports whether the workspace's entry for repo runs
// install-pre-commit-hooks: some per-repo hook has a {nix_run
// install-pre-commit-hooks} run entry. That is what "declared" means for the
// bundle doctor checks (design 7.4): the workspace has opted the repo into
// having its hooks installed, so their absence is a finding.
func (ws *Workspace) installHookDeclared(repo string) bool {
	for _, h := range ws.config.Repos[repo].Hooks {
		for _, raw := range h.Run {
			for _, attr := range nixRunAttrsIn(raw) {
				if attr == installPreCommitHooksAttr {
					return true
				}
			}
		}
	}
	return false
}

// bundleHookFindings audits one DECLARED repo's hook bundle. ok is false when
// the repo is not in bundle mode, so the caller falls back to the legacy
// pre-commit-hook-live audit. Bundle mode means the checkout holds a bundle
// pointer (even an invalid one), or it has neither a pointer nor a legacy .pre-commit-config.yaml
// (declared but never installed). A repo with no pointer and a legacy config
// (even a dangling one) is unconverted; so is the shim experiment's repo, whose
// core.hooksPath=.githooks reads as unreachable but is covered by
// git-hooks-shim-wired.
func (ws *Workspace) bundleHookFindings(repo, repoDir string) ([]Finding, bool) {
	state, info, err := ReadHookBundleState(repoDir)
	if err != nil {
		return nil, false
	}
	if info.Gen == "" && info.BrokenReason == "" && preCommitConfigDeclared(repoDir) {
		return nil, false
	}
	c, err := readHookGitContext(repoDir)
	if err != nil {
		return nil, false
	}
	canonical := c.canonical()
	installCmd := fmt.Sprintf("(cd %s && nix run .#install-pre-commit-hooks)", canonical)
	reinstall := installCmd
	if info.Gen != "" {
		if line := readFirstLine(filepath.Join(info.Dir, "reinstall")); line != "" {
			reinstall = line
		}
	}
	// A rebuild is a nix build; agents run it through bgrun (design 5.4).
	finding := func(msg, manual string) Finding {
		return Finding{
			CheckID: "pre-commit-hook-live", Repo: repo, Severity: SevError,
			Message: fmt.Sprintf("pg-hooks: repo %q: %s", repo, msg), Manual: manual,
		}
	}

	var out []Finding
	switch {
	case info.BrokenReason != "" && info.Gen == "":
		out = append(out, finding(
			fmt.Sprintf("hook bundle is broken (%s)", info.BrokenReason),
			"rebuild:  "+installCmd,
		))
	case info.Gen == "":
		// No pointer: no bundle, so stubs and stages are unknowable.
		out = append(out, finding(
			"no hook bundle (no pg-hooks/current pointer); hooks are not run on commit",
			"install it:  "+installCmd,
		))
	case state == HookBundleRelocated:
		out = append(out, finding(
			fmt.Sprintf("this clone moved from %s; its bundle is no longer GC-rooted", info.ClonePath),
			"rebuild:  "+reinstall,
		))
	case info.BrokenReason != "":
		out = append(out, finding(
			fmt.Sprintf("hook bundle is broken (%s)", info.BrokenReason),
			"rebuild:  "+reinstall,
		))
	case info.Bundle == "":
		out = append(out, finding(
			fmt.Sprintf("hook bundle is broken (%s/%s/bundle is missing: its GC root dangles)", info.Dir, info.Gen),
			"rebuild:  "+reinstall,
		))
	}

	if state == HookBundleUnreachable {
		manual := fmt.Sprintf("operator:  git -C %s config --local --unset core.hooksPath", canonical)
		if info.UnreachableOrigin != filepath.Join(c.Common, "config") {
			manual = fmt.Sprintf("operator:  remove core.hooksPath=%s from %s", info.UnreachableValue, info.UnreachableOrigin)
		}
		out = append(out, finding(
			fmt.Sprintf("git does not run hooks from %s (core.hooksPath=%s from %s)",
				filepath.Join(c.Common, "hooks"), info.UnreachableValue, info.UnreachableOrigin),
			manual,
		))
	}

	// Stubs: every stage the bundle has hooks for must hold an executable stub
	// carrying the marker. Only checkable with a usable bundle (stages.json).
	if info.Bundle != "" {
		if bad := badHookStubs(filepath.Join(c.Common, "hooks"), bundleStages(info.Bundle)); len(bad) > 0 {
			out = append(out, finding(
				fmt.Sprintf("hook stubs in %s are not pg-hooks stubs for: %s; those stages do not run the bundle",
					filepath.Join(c.Common, "hooks"), strings.Join(bad, ", ")),
				"reinstall (a foreign file at a needed stage must be moved aside first):  "+reinstall,
			))
		}
	}
	return out, true
}

// readFirstLine returns the first line of path, "" when unreadable.
func readFirstLine(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	line, _, _ := strings.Cut(string(data), "\n")
	return strings.TrimSpace(line)
}

// bundleStages returns the sorted stages the bundle has hooks for (the keys of
// stages.json), defaulting to {"pre-commit"} when the file is unreadable.
func bundleStages(bundle string) []string {
	data, err := os.ReadFile(filepath.Join(bundle, "stages.json"))
	if err == nil {
		var m map[string]json.RawMessage
		if json.Unmarshal(data, &m) == nil && len(m) > 0 {
			out := make([]string, 0, len(m))
			for k := range m {
				out = append(out, k)
			}
			sort.Strings(out)
			return out
		}
	}
	return []string{"pre-commit"}
}

// badHookStubs names every stage in hooksDir whose stub is missing, a
// directory, not executable, or not owned by pg-hooks ("legacy prek stub" for
// prek's own, "foreign" for any other file).
func badHookStubs(hooksDir string, stages []string) []string {
	var bad []string
	for _, stage := range stages {
		p := filepath.Join(hooksDir, stage)
		info, err := os.Stat(p)
		if err != nil {
			bad = append(bad, stage+" (missing)")
			continue
		}
		if info.IsDir() {
			bad = append(bad, stage+" (foreign: a directory)")
			continue
		}
		data, err := os.ReadFile(p)
		if err != nil {
			bad = append(bad, stage+" (unreadable)")
			continue
		}
		switch {
		case !hasLine(string(data), hookStubMarker):
			if strings.Contains(string(data), hookLegacyStubMarker) {
				bad = append(bad, stage+" (legacy prek stub, no pg-hooks marker)")
			} else {
				bad = append(bad, stage+" (foreign file, no pg-hooks marker)")
			}
		case info.Mode()&0o111 == 0:
			bad = append(bad, stage+" (not executable)")
		}
	}
	return bad
}

// hasLine reports whether text has a line equal to want.
func hasLine(text, want string) bool {
	for _, ln := range strings.Split(text, "\n") {
		if strings.TrimRight(ln, "\r ") == want {
			return true
		}
	}
	return false
}
