name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nix-checks:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Setup Nix store cache
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
        with:
          ignore-missing-flake-lock: false
          fail-mode: true
          send-statistics: false

      - name: Check formatting with treefmt
        run: |
          nix fmt -- --ci

      - name: Run nix flake check
        run: nix flake check --show-trace -L
